### ISSUE TITLE
Please upgrade the Vivid repo for the current buildfarm

### ISSUE THREAD

**Issue by vrabaud** [ros-infrastructure/ros_buildfarm_config#2]
I know, I know, it's not even released yet so feel free to discard but you'll have to do it at some point :)

I am tracking a weird bug and trying on as many configs as possible. The current Vivid on the farm is really our of sync and that forces me to recompile the whole ROS (because of log4cxx and OpenCV issues). Thx

Otherwise, please upgrade at a strategic moment: https://wiki.ubuntu.com/VividVervet/ReleaseSchedule (if not Alpha2, Beta1 ?)

**Comment by tfoote** [comment]
Can you clarify what packages are out of date? We only import these packages into our system. https://github.com/ros-infrastructure/buildfarm_deployment_config/blob/master/repo/common.yaml#L132

Everything else comes from the upstream repos.

**Comment by vrabaud** [comment]
ok, I thought you had your own mirrors.
As expected, the error was on my side: getting trusty binaries on vivid ..............
Thx and sorry for the noise !
