### ISSUE TITLE
change / document branches

### ISSUE THREAD

**Issue by dirk-thomas** [ros-infrastructure/ros_buildfarm_config#23]
It is rather intuitive that the default branch is not the one being used. The existence of the `production` branch is neither visible nor discoverable to users.

Please either:
- document the `production` branch in the README on the master branch and in a CONTRIBUTING file or
- (much preferred) rename the `master` branch to `testing` and `production` to `master`

**Comment by tfoote** [comment]
The production branch is somewhat specifically designed to be less discoverable by users. We don't want people forking from production.

**Comment by tfoote** [comment]
fixed in #48
