### ISSUE TITLE
blacklist a package build for a Ubuntu distro

### ISSUE THREAD

**Issue by asmodehn** [ros-infrastructure/ros_buildfarm_config#74]
I want to blacklist a package for a Ubuntu distro (all saucy builds of my packages for example, since saucy is EOL)...
Is there a way to do this ?

The readme describe only how to blacklist a package for a target platform for a ROS distro.

**Comment by dirk-thomas** [comment]
The buildfarm only allows to blacklist packages per build file. In your case a single build file is used for Saucy as well as Trusty (https://github.com/ros-infrastructure/ros_buildfarm_config/blob/a0cb901eaadeda368ca7e892cda64abd2178ba83/indigo/release-build.yaml#L53-L59).

Please see a previous discussion about disabling building for EOL Ubuntu distro all together: https://discourse.ros.org/t/drop-support-for-wily/727/

So currently the answer, no, this is not possible. But hopefully it will be in the future.

**Comment by dirk-thomas** [comment]
We finally are able to stop building for EOL Ubuntu distros, see https://discourse.ros.org/t/suspension-of-debian-packaging-for-eold-distros-saucy-utopic-vivid-and-wily/1601 That should achieve your original request I assume.
